#ifndef __file_headers_H
#define __file_headers_H

static uint8_t fileHeader[] = "DynamisPRC - Politecnico di Milano;\n";
static uint8_t channelNameHeader[] = "TIMESTAMP;HALL_EFFECT_FR;HALL_EFFECT_FL;HALL_EFFECT_RR;HALL_EFFECT_RL;T_H20_SX_IN;T_H20_SX_OUT;T_H20_DX_IN;\
																			T_H20_DX_OUT;T_OIL_IN;T_OIL_OUT;T_H20_ENGINE;BATTERY_VOLTAGE;GEAR;RPM;TPS1;PH2O;VH_SPEED;SLIP_TARGET;SLIP;\
																			MANUAL_LIMITER_ACTIVE;FAN;H20_PUMP_DUTY_CYCLE;PIT_LANE_ACTIVE;FUEL_PRESSURE;OIL_PRESSURE;LAMBDA;FLAG_SMOT;\
																			L_FUEL;T_SCARICO_1;T_SCARICO_2;LINEARE_FR;LOAD_CELL_FR;BPS_FRONT;APPS;LINEARE_FL;LOAD_CELL_FL;BPS_REAR;\
																			STEERING_WHEEL_ANGLE;LINEARE_RL;LOAD_CELL_RL;LINEARE_RR;LOAD_CELL_RR;IR1_FL;IR2_FL;IR3_FL;BRAKE_IR_FL;\
																			IR1_FR;IR2_FR;IR3_FR;BRAKE_IR_FR;IR1_RL;IR2_RL;IR3_RL;BRAKE_IR_RL;IR1_RR;IR2_RR;IR3_RR;BRAKE_IR_RR;IMU1_ACC_X;\
																			IMU1_ACC_Y;IMU1_GYR_X;IMU1_GYR_Z;IMU1_HEADING;IMU1_ACC_Z;IMU1_GYR_Y;IMU1_SENSORS_CALIBRATION;IMU2_ACC_X;\
																			IMU2_ACC_Y;IMU2_GYR_X;IMU2_GYR_Z;IMU2_HEADING;IMU2_ACC_Z;IMU2_GYR_Y;IMU2_SENSORS_CALIBRATION;IMU_DCU_ACC_X;\
																			IMU_DCU_ACC_Y;IMU_DCU_GYR_X;IMU_DCU_GYR_Z;IMU_DCU_HEADING;IMU_DCU_ACC_Z;IMU_DCU_GYR_Y;IMU_DCU_SENSORS_CALIBRATION;\
																			GPS_LATITUDE_MINUTES;GPS_LONGITUDE_MINUTES;GPS_SPEED;DAU_FR_TEMP;DAU_FR_CURRENT;DAU_FL_TEMP;DAU_FL_CURRENT;\
																			DAU_REAR_TEMP;DAU_REAR_CURRENT;SW_TEMP;SW_CURRENT;GCU_TEMP;GCU_CURR;H2O_PUMP_CURRENT;FUEL_PUMP_CURRENT;\
																			GEARMOTOR_CURRENT;CLUTCH_CURRENT;FAN_SX_CURRENT;FAN_DX_CURRENT;DCU_TEMP;DCU_CURRENT;XBEE_CURRENT;DUC_3V3_CURRENT;\
																			DCU_12V_VOLTAGE;DCU_5V_VOLTAGE;DCU_3V3_VOLTAGE;\n";

#endif
